### ISSUE TITLE
something wrong when I run `gulp`

### ISSUE THREAD

**Issue by sincerefly** [jhabdas/material-ui-example#3]
```text
[15:35:39] Using gulpfile ~/test/material-ui-example/gulpfile.js
[15:35:39] Starting 'setWatch'...
[15:35:39] Finished 'setWatch' after 55 μs
[15:35:39] Starting 'browserify'...
[15:35:39] Bundling app.js...
[15:35:39] Starting 'markup'...
[15:35:39] Starting 'less'...
[15:35:39] Starting 'fonts'...
[15:35:39] Starting 'muiFonts'...
[15:35:39] Finished 'fonts' after 12 ms
[15:35:39] Finished 'muiFonts' after 12 ms
[15:35:39] gulp-notify: [Compile Error] 'node_modules/material-ui/src/less/components.less' wasn't found. Tried - /home/sincerefly/test/material-ui-example/src/less/node_modules/material-ui/src/less/components.less,node_modules/material-ui/src/less/components.less in file /home/sincerefly/test/material-ui-example/src/less/main.less line no. 7
[15:35:39] Finished 'less' after 57 ms
[15:35:39] Finished 'markup' after 75 ms
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: watch /home/sincerefly/test/material-ui-example/node_modules/react/lib/validateDOMNesting.js ENOSPC
    at exports._errnoException (util.js:860:11)
    at FSWatcher.start (fs.js:1313:19)
    at Object.fs.watch (fs.js:1341:11)
    at createFsWatchInstance (/home/sincerefly/test/material-ui-example/node_modules/chokidar/lib/nodefs-handler.js:24:15)
    at setFsWatchListener (/home/sincerefly/test/material-ui-example/node_modules/chokidar/lib/nodefs-handler.js:47:19)
    at EventEmitter.NodeFsHandler._watchWithNodeFs (/home/sincerefly/test/material-ui-example/node_modules/chokidar/lib/nodefs-handler.js:177:15)
    at EventEmitter.NodeFsHandler._handleFile (/home/sincerefly/test/material-ui-example/node_modules/chokidar/lib/nodefs-handler.js:201:8)
    at EventEmitter.<anonymous> (/home/sincerefly/test/material-ui-example/node_modules/chokidar/lib/nodefs-handler.js:353:12)
    at FSReqWrap.oncomplete (fs.js:82:15)

```

**Comment by sincerefly** [comment]
I solved it on Fedora 22

```bash
```

**Comment by sincerefly** [comment]
but still can't find `components.less`

**Comment by jhabdas** [comment]
Please fork this repo because I'm going to delete it soon

**Comment by jhabdas** [comment]
Here's some background as to why:

https://github.com/jhabdas/material-ui-example/issues/2#issuecomment-155247442

Best of luck!

**Comment by jhabdas** [comment]
Repository scheduled for deletion two days

**Comment by sincerefly** [comment]
Thx a lot :+1:
